version: "3.8"

services:
  general-db:
    image: postgres:14.7
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: general
      POSTGRES_DB: general
    volumes:
      - general-db:/var/lib/postgresql/data
    ports:
      - 9999:5432
    networks:
      - skripsi-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M
  longterm-db:
    image: postgres:14.7
    shm_size: 2g
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: longterm
      POSTGRES_DB: longterm
    volumes:
      - longterm-db:/var/lib/postgresql/data
    ports:
      - 9000:5432
    networks:
      - skripsi-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4096M
  sharding-oneday-db:
    image: postgres:14.7
    shm_size: 1g
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: sharding
      POSTGRES_DB: sharding
    volumes:
      - sharding-oneday-db:/var/lib/postgresql/data
    ports:
      - 9001:5432
    networks:
      - skripsi-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
  sharding-sevenday-db:
    image: postgres:14.7
    shm_size: 1g
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: sharding
      POSTGRES_DB: sharding
    volumes:
      - sharding-sevenday-db:/var/lib/postgresql/data
    ports:
      - 9002:5432
    networks:
      - skripsi-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
  sharding-thirtyday-db:
    image: postgres:14.7
    shm_size: 1g
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: sharding
      POSTGRES_DB: sharding
    volumes:
      - sharding-thirtyday-db:/var/lib/postgresql/data
    ports:
      - 9003:5432
    networks:
      - skripsi-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
  sharding-ninetyday-db:
    image: postgres:14.7
    shm_size: 1g
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: sharding
      POSTGRES_DB: sharding
    volumes:
      - sharding-ninetyday-db:/var/lib/postgresql/data
    ports:
      - 9004:5432
    networks:
      - skripsi-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - skripsi-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.100.0.100:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      skripsi-network:
        ipv4_address: "172.100.0.100"
    healthcheck:
      test: ["CMD", "nc", "-z", "zookeeper", "2181"]
      interval: 10s
      timeout: 5s
      retries: 20
  # kafka2:
  #   image: confluentinc/cp-kafka:latest
  #   ports:
  #     - "9093:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.100.0.100:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   depends_on:
  #     zookeeper:
  #       condition: service_healthy
  #   networks:
  #     skripsi-network:
  #       ipv4_address: "172.100.0.200"
  #   healthcheck:
  #     test: ["CMD", "nc", "-z", "zookeeper", "2181"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 20
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9100:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      kafka1:
        condition: service_healthy
      # kafka2:
      #   condition: service_healthy
    networks:
      - skripsi-network

volumes:
  general-db:
  longterm-db:
  sharding-oneday-db:
  sharding-sevenday-db:
  sharding-thirtyday-db:
  sharding-ninetyday-db:

networks:
  skripsi-network:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
